#!/usr/bin/env bash
# Generate Cilium CNI manifest for e2e ClusterResourceSet.
# Accepts CILIUM_VERSION env var.
# Skips generation if bases/cni.yaml already contains the matching version.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

CILIUM_VERSION="${CILIUM_VERSION:-1.19.2}"
E2E_TEMPLATES="${REPO_ROOT}/test/e2e/data/infrastructure-cloudscale"
CNI_FILE="${E2E_TEMPLATES}/bases/cni.yaml"

# Check if the file already contains the matching version
if [ -f "${CNI_FILE}" ] && grep -q "# Cilium version: ${CILIUM_VERSION}" "${CNI_FILE}"; then
  echo "CNI manifest already at version ${CILIUM_VERSION}, skipping."
  exit 0
fi

echo "Generating Cilium CNI manifest (version ${CILIUM_VERSION})..."

helm repo add cilium https://helm.cilium.io/ 2>/dev/null || true
helm repo update cilium

CILIUM_YAML=$(helm template cilium cilium/cilium --version "${CILIUM_VERSION}" --namespace kube-system \
  --set ipam.mode=kubernetes \
  --set routingMode=tunnel \
  --set tunnelProtocol=vxlan \
  --set kubeProxyReplacement=true \
  --set hubble.enabled=false \
  --set hubble.relay.enabled=false \
  --set hubble.ui.enabled=false \
  --set operator.replicas=1 \
  --set envoy.enabled=false \
  --set l7Proxy=false 2>/dev/null | sed '/^#/d; /^[[:space:]]*#/d; s/\${BIN_PATH}/\$\${BIN_PATH}/g' | cat -s)

mkdir -p "$(dirname "${CNI_FILE}")"

cat > "${CNI_FILE}" <<EOF
# Cilium CNI resources for ClusterResourceSet
# Automatically deployed to workload clusters with label: cni=cilium
# Regenerate with: make generate-e2e-cni
# Code generated by generate-e2e-cni.sh. DO NOT EDIT.
# Cilium version: ${CILIUM_VERSION}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "\${CLUSTER_NAME}-cni"
  namespace: "\${NAMESPACE}"
data:
  cilium.yaml: |
$(echo "${CILIUM_YAML}" | sed 's/^/    /')
---
apiVersion: addons.cluster.x-k8s.io/v1beta2
kind: ClusterResourceSet
metadata:
  name: "\${CLUSTER_NAME}-cni"
  namespace: "\${NAMESPACE}"
spec:
  strategy: ApplyOnce
  clusterSelector:
    matchLabels:
      cni: cilium
  resources:
    - name: "\${CLUSTER_NAME}-cni"
      kind: ConfigMap
EOF

echo "CNI manifest generated successfully."
