#!/usr/bin/env bash
# Generate cloudscale CCM manifest for e2e ClusterResourceSet.
# Accepts CCM_VERSION env var (default: 1.3.0).
# Skips generation if bases/ccm.yaml already contains the matching version.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

CCM_VERSION="${CCM_VERSION:-1.3.0}"
E2E_TEMPLATES="${REPO_ROOT}/test/e2e/data/infrastructure-cloudscale"
CCM_FILE="${E2E_TEMPLATES}/bases/ccm.yaml"

# Check if the file already contains the matching version
if [ -f "${CCM_FILE}" ] && grep -q "quay.io/cloudscalech/cloudscale-cloud-controller-manager:${CCM_VERSION}" "${CCM_FILE}"; then
  echo "CCM manifest already at version ${CCM_VERSION}, skipping."
  exit 0
fi

echo "Generating CCM manifest (version ${CCM_VERSION})..."

CCM_YAML=$(curl -LsS "https://github.com/cloudscale-ch/cloudscale-cloud-controller-manager/releases/download/${CCM_VERSION}/config.yml")

mkdir -p "$(dirname "${CCM_FILE}")"

cat > "${CCM_FILE}" <<'OUTER'
# Cloud Controller Manager resources for ClusterResourceSet
# Automatically deployed to workload clusters with label: ccm=cloudscale
# Regenerate with: make generate-e2e-ccm
# Code generated by generate-e2e-ccm.sh. DO NOT EDIT.
OUTER

cat >> "${CCM_FILE}" <<EOF
# CCM version: ${CCM_VERSION}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "\${CLUSTER_NAME}-ccm"
  namespace: "\${NAMESPACE}"
data:
  ccm.yaml: |
    ---
$(echo "${CCM_YAML}" | sed 's/^/    /')
---
apiVersion: v1
kind: Secret
metadata:
  name: "\${CLUSTER_NAME}-ccm-credentials"
  namespace: "\${NAMESPACE}"
type: addons.cluster.x-k8s.io/resource-set
stringData:
  secret.yaml: |
    apiVersion: v1
    kind: Secret
    metadata:
      name: cloudscale
      namespace: kube-system
    type: Opaque
    stringData:
      access-token: "\${CLOUDSCALE_API_TOKEN}"
---
apiVersion: addons.cluster.x-k8s.io/v1beta2
kind: ClusterResourceSet
metadata:
  name: "\${CLUSTER_NAME}-ccm"
  namespace: "\${NAMESPACE}"
spec:
  strategy: ApplyOnce
  clusterSelector:
    matchLabels:
      ccm: cloudscale
  resources:
    - name: "\${CLUSTER_NAME}-ccm-credentials"
      kind: Secret
    - name: "\${CLUSTER_NAME}-ccm"
      kind: ConfigMap
EOF

echo "CCM manifest generated successfully."
