apiVersion: v1
kind: Secret
metadata:
  name: "${CLUSTER_NAME}-credentials"
  namespace: "${NAMESPACE}"
type: Opaque
stringData:
  token: "${CLOUDSCALE_API_TOKEN}"
---
apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: "${CLUSTER_NAME}"
  namespace: "${NAMESPACE}"
  labels:
    ccm: cloudscale
spec:
  clusterNetwork:
    pods:
      cidrBlocks: ["192.168.0.0/16"]
    services:
      cidrBlocks: ["10.96.0.0/12"]
    serviceDomain: "cluster.local"
  topology:
    classRef:
      name: quick-start
      namespace: "${NAMESPACE}"
    version: "${KUBERNETES_VERSION}"
    controlPlane:
      replicas: ${CONTROL_PLANE_MACHINE_COUNT:=1}
    workers:
      machineDeployments:
        - class: worker
          name: md-0
          replicas: ${WORKER_MACHINE_COUNT:=2}
    variables:
      - name: region
        value: "${CLOUDSCALE_REGION}"
      - name: cloudscaleControlPlaneMachineFlavor
        value: "${CLOUDSCALE_CONTROL_PLANE_MACHINE_FLAVOR}"
      - name: cloudscaleControlPlaneMachineImage
        value: "${CLOUDSCALE_MACHINE_IMAGE}"
      - name: cloudscaleControlPlaneMachineRootVolumeSize
        value: ${CLOUDSCALE_ROOT_VOLUME_SIZE}
      - name: cloudscaleControlPlaneServerGroupName
        value: "${CLUSTER_NAME}-cp"
      - name: cloudscaleWorkerMachineFlavor
        value: "${CLOUDSCALE_WORKER_MACHINE_FLAVOR}"
      - name: cloudscaleWorkerMachineImage
        value: "${CLOUDSCALE_MACHINE_IMAGE}"
      - name: cloudscaleWorkerMachineRootVolumeSize
        value: ${CLOUDSCALE_ROOT_VOLUME_SIZE}
      - name: cloudscaleWorkerServerGroupName
        value: "${CLUSTER_NAME}-mp-0"
      - name: credentialsRefName
        value: "${CLUSTER_NAME}-credentials"
      - name: cloudscaleSSHKeys
        value:
          - "${CLOUDSCALE_SSH_PUBLIC_KEY}"